sudo: required
services: docker
language: bash
env:
  matrix:
    - TARGET=stage3-amd64 EBUILD="frr-9999"
    - TARGET=stage3-amd64 EBUILD="rtrlib-9999"
    - TARGET=stage3-amd64 EBUILD="libyang-9999"
    - TARGET=stage3-amd64-hardened EBUILD="frr-9999"
    - TARGET=stage3-amd64-hardened EBUILD="rtrlib-9999"
    - TARGET=stage3-amd64-hardened EBUILD="libyang-9999"
    - TARGET=stage3-amd64-hardened-nomultilib EBUILD="frr-9999"
    - TARGET=stage3-amd64-hardened-nomultilib EBUILD="rtrlib-9999"
    - TARGET=stage3-amd64-hardened-nomultilib EBUILD="libyang-9999"
    - TARGET=stage3-amd64-nomultilib EBUILD="frr-9999"
    - TARGET=stage3-amd64-nomultilib EBUILD="rtrlib-9999"
    - TARGET=stage3-amd64-nomultilib EBUILD="libyang-9999"
    - TARGET=stage3-x86 EBUILD="frr-9999"
    - TARGET=stage3-x86 EBUILD="rtrlib-9999"
    - TARGET=stage3-x86 EBUILD="libyang-9999"
    - TARGET=stage3-x86-hardened EBUILD="frr-9999"
    - TARGET=stage3-x86-hardened EBUILD="rtrlib-9999"
    - TARGET=stage3-x86-hardened EBUILD="libyang-9999"

script:
  - wget https://raw.githubusercontent.com/FRRouting/gentoo-overlay/ci/ci.sh
  - chmod +x ci.sh
  - ./ci.sh _preflight
